question_data = [
    {
        "category": "Politics", "type": "multiple", "difficulty": "medium",
        "question": "Which president erased the national debt of the United States?",
        "correct_answer": "Andrew Jackson",
        "incorrect_answers": ["Ronald Reagan", "John F. Kennedy", "Franklin Roosevelt"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "&quot;Half-Life 2&quot; runs on the Source Engine.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Science & Nature", "type": "multiple", "difficulty": "medium",
            "question": "Who developed the first successful polio vaccine in the 1950s?",
            "correct_answer": "Jonas Salk",
            "incorrect_answers": ["John F. Enders", "Thomas Weller", "Frederick Robbins"]},
        {"category": "Science & Nature", "type": "multiple", "difficulty": "medium",
            "question": "The medical condition osteoporosis affects which part of the body?",
            "correct_answer": "Bones", "incorrect_answers": ["Skin", "Brain", "Heart"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "In the game &quot;Subnautica&quot;, a &quot;Spadefish&quot; will attack you.",
            "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Mythology", "type": "multiple", "difficulty": "medium",
            "question": "A minotaur is half human half what?", "correct_answer": "Bull",
            "incorrect_answers": ["Cow", "Horse", "Eagle"]},
        {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
            "question": "What is the main CPU is the Sega Mega Drive \/ Sega Genesis?",
            "correct_answer": "Motorola 68000",
            "incorrect_answers": ["Zilog Z80", "Yamaha YM2612", "Intel 8088"]},
        {"category": "Entertainment: Film", "type": "multiple", "difficulty": "easy",
            "question": "In the 1995 film &quot;Balto&quot;, who are Steele&#039;s accomplices?",
            "correct_answer": "Kaltag, Nikki, and Star",
            "incorrect_answers": ["Dusty, Kirby, and Ralph", "Nuk, Yak, and Sumac",
             "Jenna, Sylvie, and Dixie"]},
        {"category": "Entertainment: Cartoon & Animations", "type": "multiple",
            "difficulty": "medium",
            "question": "In &quot;SpongeBob SquarePants&quot;, what is the name of Sandy Cheek&#039;s place of residence?",
            "correct_answer": "Sandy&#039;s Treedome",
            "incorrect_answers": ["&quot;The Dome&quot;", "Sandy&#039;s Bubble",
                                                            "Auquatic Reseach Centre"]},
            {"category": "Entertainment: Video Games", "type": "multiple",
            "difficulty": "easy",
            "question": "In the video game franchise &quot;Halo&quot;, what is the UNSC&#039;s main opposing faction called?",
            "correct_answer": "The Covenant",
            "incorrect_answers": ["The Reckoning", "The Peoples", "The Slaughterers"]}]
